[workspace]
members = [
    "keycodemap",
    "qemu-display-listener",
    "qemu-gtk4",
    "xtask",
]

[patch.crates-io]
zbus = { path = '/home/elmarco/src/zbus/zbus' }
zvariant = { path = '/home/elmarco/src/zbus/zvariant' }
