[workspace]
members = [
    "keycodemap",
    "qemu-display-listener",
    "qemu-rdw",
    "qemu-vnc",
    "xtask",
]

default-members = ["qemu-rdw"]

[patch.crates-io]
zbus = { git = 'https://gitlab.freedesktop.org/dbus/zbus.git' }
zvariant = { git = 'https://gitlab.freedesktop.org/dbus/zbus.git' }
vnc = { git = 'https://github.com/elmarco/rust-vnc', branch = 'server' }
