[workspace]
members = [
    "keycodemap",
    "qemu-display-listener",
    "qemu-rdw",
    "qemu-vnc",
    "xtask",
]

default-members = ["qemu-rdw"]

[patch.crates-io]
zbus = { git = 'https://gitlab.freedesktop.org/elmarco/zbus.git', branch = 'proxy-prop' }
zvariant = { git = 'https://gitlab.freedesktop.org/elmarco/zbus.git', branch = 'proxy-prop' }
vnc = { git = 'https://github.com/elmarco/rust-vnc', branch = 'server' }

[patch."https://gitlab.gnome.org/malureau/rdw.git"]
rdw = { path = '/home/elmarco/src/rdw/rdw' }
